name: Create nightly release

on:
  schedule:
    - cron: "0 5 * * *"  # runs at 5 AM UTC

jobs:
  nightly-release:
    name: "Nightly Release"
    runs-on: "ubuntu-latest"

    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Release"
